server:
  port: 8081

spring:
  application:
    name: groupproject

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ledger?useSSL=false&serverTimezone=America/New_York&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASS:}

  jackson:
    default-property-inclusion: non_null

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

mybatis-plus:
  type-aliases-package: dev.coms4156.project.groupproject.entity

logging:
  level:
    dev.coms4156.project.groupproject: debug
    dev.coms4156.project.groupproject.access: info
